### ISSUE TITLE
Support of rgba with variables

### ISSUE THREAD

**Issue by awolkers** [AndyOGo/stylelint-declaration-strict-value#12]
Can you add the support of the use of variables in combination with for instance rgba.

`background-color: rgba($color-foo, .5);`

**Comment by AndyOGo** [comment]
@awolkers 
May I ask you to provide more details? A failing test would be perfect.
According to my tests this should work - https://github.com/AndyOGo/stylelint-declaration-strict-value/blob/master/test/default.js

**Comment by awolkers** [comment]
CSS:
```
.area {
    padding: 1px 0;

    &-gray {
        background-color: rgba($color-cool-gray-light, 0.4);
    }
}
```
Config:
```
scale-unlimited/declaration-strict-value:
        - /color/
        -
            ignoreFunctions: false
            ignoreKeywords:
                - currentColor
                - transparent
                - inherit
            ignoreVariables: true
```
Error:
```
Expected variable or keyword for "rgba($color-cool-gray-light, 0.4)" of "background-color"   scale-unlimited/declaration-strict-value
```
