### ISSUE TITLE
font-size: smaller lints an error

### ISSUE THREAD

**Issue by AndyOGo** [AndyOGo/stylelint-declaration-strict-value#17]
```css
.foo {
  font-size: smaller;
}
```

> 36:7  ✖  Expected variable, function or keyword for "smaller" of "font-size"   scale-unlimited/declaration-strict-value
